import { Wallet } from 'ethers';
import fs from 'fs';
import path from 'path';

/**
 * Generates the protocol wallets used by HNTRMembership:
 * - Company Wallet   (receives the 25% protocol cut + commission breakage)
 * - Leadership Wallet (5% leadership pool)
 * - Rank Wallet      (5% rank-bonus pool)
 * - Pool Wallet      (20% locked portion of commissions)
 * - Security Wallet  (sweeps overdue, never-claimed commissions back to members;
 *                     admin-signed in the UI — NO backend key)
 * - Burner Wallet    (server hot key: voucher redemption + commission signer +
 *                     overrideMembershipTier + leadership/rank/pool disbursement hop-2)
 *
 * Make sure to securely store the private keys outputted by this function!
 * Running this script also writes a ready-to-use .env block to
 * `generated-wallets.env` (gitignored). The backend only ever needs the BURNER key;
 * every other key stays in a secrets manager / the admin's own wallet.
 */
export function generateProtocolWallets() {
  const companyWallet = Wallet.createRandom();
  const leadershipWallet = Wallet.createRandom();
  const rankWallet = Wallet.createRandom();
  const poolWallet = Wallet.createRandom();
  const securityWallet = Wallet.createRandom();
  const burnerWallet = Wallet.createRandom();

  const wallets = {
    company: { address: companyWallet.address, privateKey: companyWallet.privateKey },
    leadership: { address: leadershipWallet.address, privateKey: leadershipWallet.privateKey },
    rank: { address: rankWallet.address, privateKey: rankWallet.privateKey },
    pool: { address: poolWallet.address, privateKey: poolWallet.privateKey },
    security: { address: securityWallet.address, privateKey: securityWallet.privateKey },
    burner: { address: burnerWallet.address, privateKey: burnerWallet.privateKey },
  };

  console.log('==========================================');
  console.log('PROTOCOL WALLETS GENERATED');
  console.log('==========================================');

  console.log('\n1. COMPANY WALLET');
  console.log(`Address:     ${wallets.company.address}`);
  console.log(`Private Key: ${wallets.company.privateKey}`);

  console.log('\n2. LEADERSHIP WALLET');
  console.log(`Address:     ${wallets.leadership.address}`);
  console.log(`Private Key: ${wallets.leadership.privateKey}`);

  console.log('\n3. RANK WALLET');
  console.log(`Address:     ${wallets.rank.address}`);
  console.log(`Private Key: ${wallets.rank.privateKey}`);

  console.log('\n4. POOL WALLET');
  console.log(`Address:     ${wallets.pool.address}`);
  console.log(`Private Key: ${wallets.pool.privateKey}`);

  console.log('\n5. SECURITY WALLET');
  console.log(`Address:     ${wallets.security.address}`);
  console.log(`Private Key: ${wallets.security.privateKey}`);

  console.log('\n6. BURNER WALLET (ETH for gas only — never tokens)');
  console.log(`Address:     ${wallets.burner.address}`);
  console.log(`Private Key: ${wallets.burner.privateKey}`);

  const outputPath = path.resolve(__dirname, '../../generated-wallets.env');
  const envBlock = [
    '# Generated by `npm run generate:wallets` - DO NOT COMMIT THIS FILE.',
    '#',
    '# --- Paste these lines into hntr/.env (used by the Foundry deploy script) ---',
    `COMPANY_WALLET=${wallets.company.address}`,
    `LEADERSHIP_WALLET=${wallets.leadership.address}`,
    `RANK_WALLET=${wallets.rank.address}`,
    `POOL_WALLET=${wallets.pool.address}`,
    `SECURITY_WALLET=${wallets.security.address}`,
    `BURNER_WALLET=${wallets.burner.address}`,
    '',
    '# --- Paste this into hntr-backend/.env (the ONLY protocol key the backend needs) ---',
    `BURNER_WALLET=${wallets.burner.address}`,
    `BURNER_WALLET_PRIVATE_KEY=${wallets.burner.privateKey}`,
    '',
    '# --- Keep the remaining private keys in a secrets manager / your own wallet. ---',
    '# --- The admin imports the company/leadership/rank/pool/security key into their ---',
    '# --- wallet to fund the burner or sign withdrawUnclaimed; none reach the backend. ---',
    `# COMPANY_WALLET_PRIVATE_KEY=${wallets.company.privateKey}`,
    `# LEADERSHIP_WALLET_PRIVATE_KEY=${wallets.leadership.privateKey}`,
    `# RANK_WALLET_PRIVATE_KEY=${wallets.rank.privateKey}`,
    `# POOL_WALLET_PRIVATE_KEY=${wallets.pool.privateKey}`,
    `# SECURITY_WALLET_PRIVATE_KEY=${wallets.security.privateKey}`,
    '',
  ].join('\n');

  fs.writeFileSync(outputPath, envBlock, { encoding: 'utf-8', mode: 0o600 });

  console.log('\n==========================================');
  console.log(`Wrote ready-to-paste .env block to: ${outputPath}`);
  console.log('IMPORTANT: Save these private keys securely, then delete generated-wallets.env.');
  console.log('You need the ADDRESSES to configure the contract (setWallets / setSecurityWallet / setBurnerWallet).');
  console.log('The backend only needs BURNER_WALLET_PRIVATE_KEY in hntr-backend/.env.');

  return wallets;
}

/** Generates only the burner hot key (for voucher redeploys without rotating protocol wallets). */
export function generateBurnerWallet() {
  const burner = Wallet.createRandom();
  const outputPath = path.resolve(__dirname, '../../generated-burner.env');
  const envBlock = [
    '# Generated by `npm run generate:burner` - DO NOT COMMIT THIS FILE.',
    `BURNER_WALLET=${burner.address}`,
    `BURNER_WALLET_PRIVATE_KEY=${burner.privateKey}`,
    '',
  ].join('\n');
  fs.writeFileSync(outputPath, envBlock, { encoding: 'utf-8', mode: 0o600 });
  console.log('==========================================');
  console.log('BURNER WALLET GENERATED');
  console.log('==========================================');
  console.log(`Address:     ${burner.address}`);
  console.log(`Private Key: ${burner.privateKey}`);
  console.log(`Wrote: ${outputPath}`);
  return { address: burner.address, privateKey: burner.privateKey };
}

if (require.main === module) {
  const mode = process.argv[2];
  if (mode === 'burner') {
    generateBurnerWallet();
  } else {
    generateProtocolWallets();
  }
}
