import { Wallet } from 'ethers';
import fs from 'fs';
import path from 'path';

/**
 * Generates the protocol wallets used by HNTRMembership:
 * - Treasury Wallet
 * - Leadership Wallet
 * - Achievement Wallet
 * - Pool Wallet (receives the 20% locked portion of commissions)
 * - Company Wallet (can withdraw overdue commissions on behalf of users)
 * - Burner Wallet (server-held hot key that pays gas for voucher redemptions)
 *
 * Make sure to securely store the private keys outputted by this function!
 * Running this script also writes a ready-to-use .env block to
 * `generated-wallets.env` (gitignored) so the addresses/keys can be copied
 * straight into `hntr/.env` (for the deploy script) and `hntr-backend/.env`
 * (for the company + burner wallet operations) without retyping anything.
 */
export function generateProtocolWallets() {
  const treasuryWallet = Wallet.createRandom();
  const leadershipWallet = Wallet.createRandom();
  const achievementWallet = Wallet.createRandom();
  const poolWallet = Wallet.createRandom();
  const companyWallet = Wallet.createRandom();
  const burnerWallet = Wallet.createRandom();

  const wallets = {
    treasury: {
      address: treasuryWallet.address,
      privateKey: treasuryWallet.privateKey,
    },
    leadership: {
      address: leadershipWallet.address,
      privateKey: leadershipWallet.privateKey,
    },
    achievement: {
      address: achievementWallet.address,
      privateKey: achievementWallet.privateKey,
    },
    pool: {
      address: poolWallet.address,
      privateKey: poolWallet.privateKey,
    },
    company: {
      address: companyWallet.address,
      privateKey: companyWallet.privateKey,
    },
    burner: {
      address: burnerWallet.address,
      privateKey: burnerWallet.privateKey,
    },
  };

  console.log('==========================================');
  console.log('PROTOCOL WALLETS GENERATED');
  console.log('==========================================');

  console.log('\n1. TREASURY WALLET');
  console.log(`Address:     ${wallets.treasury.address}`);
  console.log(`Private Key: ${wallets.treasury.privateKey}`);

  console.log('\n2. LEADERSHIP WALLET');
  console.log(`Address:     ${wallets.leadership.address}`);
  console.log(`Private Key: ${wallets.leadership.privateKey}`);

  console.log('\n3. ACHIEVEMENT WALLET');
  console.log(`Address:     ${wallets.achievement.address}`);
  console.log(`Private Key: ${wallets.achievement.privateKey}`);

  console.log('\n4. POOL WALLET');
  console.log(`Address:     ${wallets.pool.address}`);
  console.log(`Private Key: ${wallets.pool.privateKey}`);

  console.log('\n5. COMPANY WALLET');
  console.log(`Address:     ${wallets.company.address}`);
  console.log(`Private Key: ${wallets.company.privateKey}`);

  console.log('\n6. BURNER WALLET (ETH for gas only — never tokens)');
  console.log(`Address:     ${wallets.burner.address}`);
  console.log(`Private Key: ${wallets.burner.privateKey}`);

  const outputPath = path.resolve(__dirname, '../../generated-wallets.env');
  const envBlock = [
    '# Generated by `npm run generate:wallets` - DO NOT COMMIT THIS FILE.',
    '#',
    '# --- Paste these lines into hntr/.env (used by the Foundry deploy script) ---',
    `TREASURY_WALLET=${wallets.treasury.address}`,
    `LEADERSHIP_WALLET=${wallets.leadership.address}`,
    `ACHIEVEMENT_WALLET=${wallets.achievement.address}`,
    `POOL_WALLET=${wallets.pool.address}`,
    `COMPANY_WALLET=${wallets.company.address}`,
    `BURNER_WALLET=${wallets.burner.address}`,
    '',
    '# --- Paste these into hntr-backend/.env ---',
    `COMPANY_WALLET_PRIVATE_KEY=${wallets.company.privateKey}`,
    `BURNER_WALLET=${wallets.burner.address}`,
    `BURNER_WALLET_PRIVATE_KEY=${wallets.burner.privateKey}`,
    '',
    '# --- Keep the remaining private keys somewhere secure (e.g. a secrets manager). ---',
    '# --- They are NOT needed by the backend at runtime, only during initial setup / payouts. ---',
    `# TREASURY_WALLET_PRIVATE_KEY=${wallets.treasury.privateKey}`,
    `# LEADERSHIP_WALLET_PRIVATE_KEY=${wallets.leadership.privateKey}`,
    `# ACHIEVEMENT_WALLET_PRIVATE_KEY=${wallets.achievement.privateKey}`,
    `# POOL_WALLET_PRIVATE_KEY=${wallets.pool.privateKey}`,
    '',
  ].join('\n');

  fs.writeFileSync(outputPath, envBlock, { encoding: 'utf-8', mode: 0o600 });

  console.log('\n==========================================');
  console.log(`Wrote ready-to-paste .env block to: ${outputPath}`);
  console.log('IMPORTANT: Save these private keys securely, then delete generated-wallets.env.');
  console.log('You will need the ADDRESSES to configure the smart contract (setWallets / setCompanyWallet / setBurnerWallet).');
  console.log('You will need COMPANY_WALLET_PRIVATE_KEY and BURNER_WALLET_PRIVATE_KEY in hntr-backend/.env.');

  return wallets;
}

/** Generates only the burner hot key (for voucher redeploys without rotating protocol wallets). */
export function generateBurnerWallet() {
  const burner = Wallet.createRandom();
  const outputPath = path.resolve(__dirname, '../../generated-burner.env');
  const envBlock = [
    '# Generated by `npm run generate:burner` - DO NOT COMMIT THIS FILE.',
    `BURNER_WALLET=${burner.address}`,
    `BURNER_WALLET_PRIVATE_KEY=${burner.privateKey}`,
    '',
  ].join('\n');
  fs.writeFileSync(outputPath, envBlock, { encoding: 'utf-8', mode: 0o600 });
  console.log('==========================================');
  console.log('BURNER WALLET GENERATED');
  console.log('==========================================');
  console.log(`Address:     ${burner.address}`);
  console.log(`Private Key: ${burner.privateKey}`);
  console.log(`Wrote: ${outputPath}`);
  return { address: burner.address, privateKey: burner.privateKey };
}

if (require.main === module) {
  const mode = process.argv[2];
  if (mode === 'burner') {
    generateBurnerWallet();
  } else {
    generateProtocolWallets();
  }
}
