import { Wallet } from 'ethers';
import fs from 'fs';
import path from 'path';

/**
 * Generates the five protocol wallets used by HNTRMembership:
 * - Treasury Wallet
 * - Leadership Wallet
 * - Achievement Wallet
 * - Pool Wallet
 * - Burner Wallet (Relayer)
 *
 * Make sure to securely store the private keys outputted by this function!
 * Running this script also writes a ready-to-use .env block to
 * `generated-wallets.env` (gitignored) so the addresses/keys can be copied
 * straight into `hntr/.env` (for the deploy script) and `hntr-backend/.env`
 * (for the burner relayer) without retyping anything.
 */
export function generateProtocolWallets() {
  const treasuryWallet = Wallet.createRandom();
  const leadershipWallet = Wallet.createRandom();
  const achievementWallet = Wallet.createRandom();
  const poolWallet = Wallet.createRandom();
  const burnerWallet = Wallet.createRandom();

  const wallets = {
    treasury: {
      address: treasuryWallet.address,
      privateKey: treasuryWallet.privateKey,
    },
    leadership: {
      address: leadershipWallet.address,
      privateKey: leadershipWallet.privateKey,
    },
    achievement: {
      address: achievementWallet.address,
      privateKey: achievementWallet.privateKey,
    },
    pool: {
      address: poolWallet.address,
      privateKey: poolWallet.privateKey,
    },
    burner: {
      address: burnerWallet.address,
      privateKey: burnerWallet.privateKey,
    },
  };

  console.log('==========================================');
  console.log('PROTOCOL WALLETS GENERATED');
  console.log('==========================================');

  console.log('\n1. TREASURY WALLET');
  console.log(`Address:     ${wallets.treasury.address}`);
  console.log(`Private Key: ${wallets.treasury.privateKey}`);

  console.log('\n2. LEADERSHIP WALLET');
  console.log(`Address:     ${wallets.leadership.address}`);
  console.log(`Private Key: ${wallets.leadership.privateKey}`);

  console.log('\n3. ACHIEVEMENT WALLET');
  console.log(`Address:     ${wallets.achievement.address}`);
  console.log(`Private Key: ${wallets.achievement.privateKey}`);

  console.log('\n4. POOL WALLET');
  console.log(`Address:     ${wallets.pool.address}`);
  console.log(`Private Key: ${wallets.pool.privateKey}`);

  console.log('\n5. BURNER WALLET (Relayer)');
  console.log(`Address:     ${wallets.burner.address}`);
  console.log(`Private Key: ${wallets.burner.privateKey}`);

  const outputPath = path.resolve(__dirname, '../../generated-wallets.env');
  const envBlock = [
    '# Generated by `npm run generate:wallets` - DO NOT COMMIT THIS FILE.',
    '#',
    '# --- Paste these five lines into hntr/.env (used by the Foundry deploy script) ---',
    `TREASURY_WALLET=${wallets.treasury.address}`,
    `LEADERSHIP_WALLET=${wallets.leadership.address}`,
    `ACHIEVEMENT_WALLET=${wallets.achievement.address}`,
    `POOL_WALLET=${wallets.pool.address}`,
    `BURNER_WALLET=${wallets.burner.address}`,
    '',
    '# --- Paste this line into hntr-backend/.env so the backend relayer can sign for the burner wallet ---',
    `PRIVATE_KEY=${wallets.burner.privateKey}`,
    '',
    '# --- Keep the remaining private keys somewhere secure (e.g. a secrets manager). ---',
    '# --- They are NOT needed by the backend at runtime, only during initial setup / payouts. ---',
    `# TREASURY_WALLET_PRIVATE_KEY=${wallets.treasury.privateKey}`,
    `# LEADERSHIP_WALLET_PRIVATE_KEY=${wallets.leadership.privateKey}`,
    `# ACHIEVEMENT_WALLET_PRIVATE_KEY=${wallets.achievement.privateKey}`,
    `# POOL_WALLET_PRIVATE_KEY=${wallets.pool.privateKey}`,
    '',
  ].join('\n');

  fs.writeFileSync(outputPath, envBlock, { encoding: 'utf-8', mode: 0o600 });

  console.log('\n==========================================');
  console.log(`Wrote ready-to-paste .env block to: ${outputPath}`);
  console.log('IMPORTANT: Save these private keys securely, then delete generated-wallets.env.');
  console.log('You will need the ADDRESSES to configure the smart contract (setWallets / setBurnerWallet).');
  console.log('You will need the BURNER PRIVATE KEY in hntr-backend/.env as PRIVATE_KEY.');

  return wallets;
}

if (require.main === module) {
  generateProtocolWallets();
}
